"""接口契约 Protocol 定义。对齐: 接口契约 V1.2 §2（11 个 Protocol）"""
from __future__ import annotations
from typing import Protocol, Any
from uuid import UUID
from pdf_sku.common.schemas import *
from pdf_sku.common.enums import *


class JobCreator(Protocol):
    """§2.1 Gateway → 创建/管理 Job"""
    async def create_job(self, file_path: str, merchant_id: str, category: str | None = None,
                         uploaded_by: str = "") -> dict: ...
    async def get_job(self, job_id: str) -> dict | None: ...
    async def cancel_job(self, job_id: str) -> bool: ...
    async def requeue_job(self, job_id: str) -> bool: ...


class DocumentEvaluator(Protocol):
    """§2.2 Evaluator → 置信度评估"""
    async def evaluate(self, job_id: str, file_hash: str, config_version: str,
                       prescan: PrescanResult) -> EvaluationDTO: ...


class PageProcessor(Protocol):
    """§2.3 Pipeline → 页面处理"""
    async def process_page(self, job_id: str, page_number: int,
                           config: ThresholdProfileDTO) -> PageResultDTO: ...


class TaskManager(Protocol):
    """§2.4 Collaboration → 任务管理"""
    async def create_task(self, job_id: str, page_number: int, task_type: HumanTaskType,
                          priority: TaskPriority, context: dict) -> str: ...
    async def assign_task(self, task_id: str, operator: str) -> bool: ...
    async def complete_task(self, task_id: str, operator: str, result: dict) -> bool: ...
    async def revert_task(self, task_id: str, operator: str, reason: str = "") -> bool: ...
    async def auto_pick_next(self, operator: str) -> dict | None: ...
    async def batch_skip(self, task_ids: list[str], operator: str, reason: str = "") -> BatchResultDTO: ...


class SKUImporter(Protocol):
    """§2.5 Output → SKU 导入"""
    async def import_sku(self, job_id: str, sku_data: dict) -> ImportResultDTO: ...
    async def sync_job(self, job_id: str) -> SyncResultDTO: ...


class ConfigProvider(Protocol):
    """§2.6 Config → 配置管理"""
    async def get_profile(self, profile_id: str, version: str | None = None) -> ThresholdProfileDTO: ...
    async def get_active_profile(self, category: str | None = None) -> ThresholdProfileDTO: ...
    async def save_profile(self, profile: ThresholdProfileDTO, change_reason: str = "") -> str: ...
    async def get_impact_preview(self, profile_id: str, threshold_a: float,
                                 threshold_b: float, threshold_pv: float) -> ImpactPreviewDTO: ...


class LLMService(Protocol):
    """§2.7 LLM Adapter → 多模型统一接口"""
    async def execute(self, template_name: str, variables: dict,
                      model: str | None = None) -> dict: ...


class FeedbackCollector(Protocol):
    """§2.8 Feedback → 校准/反馈"""
    async def record_correction(self, annotation_id: str, original: dict, corrected: dict) -> None: ...
    async def submit_upgrade_suggestion(self, attr_name: str, suggested_type: str,
                                        merchant_id: str | None = None,
                                        source_count: int = 0) -> str: ...


class StorageProvider(Protocol):
    """§2.9 Storage → 文件存储"""
    async def save_file(self, path: str, data: bytes) -> str: ...
    async def read_file(self, path: str) -> bytes: ...
    async def delete_file(self, path: str) -> bool: ...
    async def get_url(self, path: str, expires: int = 3600) -> str: ...


class SSEPublisher(Protocol):
    """§2.10 SSE → 事件发布"""
    async def publish(self, job_id: str, event_type: SSEEventType, data: dict) -> None: ...


class AnnotationService(Protocol):
    """§2.11 Annotation → 独立标注"""
    async def create_annotation(self, job_id: str, page_number: int, anno_type: AnnotationType,
                                payload: dict, task_id: str | None = None,
                                operator: str = "") -> str: ...
