"""add_review_pages_columns

Revision ID: e04905bbfd43
Revises: 003
Create Date: 2026-02-27 01:26:40.371431
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e04905bbfd43'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'evaluations', ['file_hash', 'config_version'])
    op.create_unique_constraint(None, 'import_dedup', ['dedup_key'])
    op.create_unique_constraint(None, 'pages', ['job_id', 'page_number', 'attempt_no'])
    op.add_column('pdf_jobs', sa.Column('review_pages', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.create_unique_constraint(None, 'sku_image_bindings', ['sku_id', 'image_id'])
    op.create_unique_constraint(None, 'threshold_profiles', ['profile_id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threshold_profiles', type_='unique')
    op.drop_constraint(None, 'sku_image_bindings', type_='unique')
    op.drop_column('pdf_jobs', 'review_pages')
    op.drop_constraint(None, 'pages', type_='unique')
    op.drop_constraint(None, 'import_dedup', type_='unique')
    op.drop_constraint(None, 'evaluations', type_='unique')
    # ### end Alembic commands ###
